### ISSUE TITLE
Interpolation issue with Hagan West Monotone Convex

### ISSUE THREAD

**Issue by bigfatwhale** [google/tf-quant-finance#64]
The following input seems to give bad output with a strange jump, 

```python
reference_times = np.array([0.08219178, 0.12328767, 0.16438356, 0.24657534, 0.32876712, 0.4109589, 0.49315068, 0.98630137, 1.02191781], dtype=np.float64)
yields = np.array([2.5e-5, 1.189e-4, 2.151e-4, 4.236e-4, 6.5e-4, 8.905e-4, 1.141e-3, 2.6321e-3, 4.366e-3], dtype=np.float64)
interp_times = np.linspace(0.1, 1.0, 100, dtype=np.float64)
interp_yields = monotone_convex.interpolate_yields(interp_times, reference_times, yields=yields)
```

Plotting it out gives, 

![image](https://user-images.githubusercontent.com/1858007/147734912-953a8d87-e9de-4162-8476-5f99bf194bcd.png)

Can someone kindly advise?

Regards,

**Comment by cyrilchim** [comment]
Hi, thank you for reporting the issue!

There was a bug in the code which is fixed in the latest [commit](https://github.com/google/tf-quant-finance/commit/8067c1f00f7ceb26dca6f5215afde5486ad0b3f0)

Using the nightly version (pip install tff-nightly), I run your code and get

<img width="449" alt="Screen Shot 2022-01-05 at 10 03 21 AM" src="https://user-images.githubusercontent.com/14253454/148199280-44e0240d-557d-42ba-879d-502f3717d843.png">

Please let me know if this solves the issue

**Comment by bigfatwhale** [comment]
Many thanks for the prompt turnaround! Let me try it out and report back :)

Cheers,

**Comment by bigfatwhale** [comment]
I've tested and the fix looks good!

Thanks
